### PR TITLE
Kinect2 added to pyrobot, tested with hardware and python2,3

### PR DESCRIPTION
**Pull request by Dhiraj100892**
## Motivation and Context

This pull request adds a Microsoft Kinect2 sensor into PyRobot

## How Has This Been Tested

This has been tested with real hardware on Linux machine running ubuntu 16.04 with ROS kinetic. It works with both python 2 & 3

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [WIP] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [WIP] I have added tests to cover my changes.
- [WIP] All new and existing tests passed.

### CODE REVIEW

**Comment by kalyanvasudev** [comment]
Thanks! Hey @Dhiraj100892, do you think it makes better sense to make a seperate camera_utils.py as most of the depth and point cloud processing code is from Locobot camera?

**Comment by kalyanvasudev** [comment]
Nvrmd they seem pretty different my bad

**Comment by taochenshh** [comment]
These files are duplicated even though there are some changes in the `kinect2/camera` file compared to the one in LoCoBot. Please consider reorganizing both camera files and reduce the amount of duplicate code.

**Comment by Dhiraj100892** [comment]
I have made the recommended changes and raised another PR

**Pull request closed without merging**
